#include "SM.h"
#include <openssl/asn1t.h>

ASN1_SEQUENCE(EC_SM2_SIG) = {
	ASN1_SIMPLE(EC_SM2_SIG, r, CBIGNUM),
	ASN1_SIMPLE(EC_SM2_SIG, s, CBIGNUM)
} ASN1_SEQUENCE_END(EC_SM2_SIG)

DECLARE_ASN1_FUNCTIONS_const(EC_SM2_SIG)
DECLARE_ASN1_ENCODE_FUNCTIONS_const(EC_SM2_SIG, EC_SM2_SIG)
IMPLEMENT_ASN1_FUNCTIONS_const(EC_SM2_SIG)
